name:                poc-interpreter
version:             0.1.0.0
github:              "dexterlb/impaler"
license:             MIT
author:              "Angel Angelov"
maintainer:          "angel@qtrp.org"
copyright:           "2022 Angel Angelov"

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/impaler>

language: GHC2021
default-extensions:
  BlockArguments
  DeriveAnyClass
  DeriveGeneric
  DerivingStrategies
  DerivingVia
  GeneralisedNewtypeDeriving
  ImportQualifiedPost
  InstanceSigs
  LambdaCase
  NamedFieldPuns
  OverloadedStrings
  ScopedTypeVariables
  StandaloneDeriving
  TupleSections
  TypeApplications
  KindSignatures
  OverloadedRecordDot
  DuplicateRecordFields
  ScopedTypeVariables
ghc-options:
  -Werror
  -Wall
  -Wcompat
  -Widentities
  -Wmissing-deriving-strategies
  -Wmissing-export-lists
  -Wpartial-fields
  -Wredundant-constraints
  -Wunused-type-patterns
  -Wincomplete-uni-patterns
  -Wunused-packages

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - parser-combinators
    - text
    - containers
    - transformers

executables:
  poc-interpreter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - poc-interpreter

tests:
  poc-interpreter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      []
#      - poc-interpreter
